package fetcher

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// GenerateLLMTxt writes extracted URLs to llm.txt file
// Format: [Link Text](URL): Context description
func GenerateLLMTxt(entries []LLMTxtEntry, outputPath string) error {
	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create llm.txt file: %w", err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	writer.WriteString("# llm.txt - Documentation URL Index\n")
	writer.WriteString("# Generated by DocFetch - List of discovered documentation URLs\n\n")

	seenURLs := make(map[string]bool)

	for _, entry := range entries {
		if entry.URL == "" {
			continue
		}

		if seenURLs[entry.URL] {
			continue
		}
		seenURLs[entry.URL] = true

		linkText := entry.Title
		if linkText == "" {
			linkText = entry.Description
		}

		cleanText := cleanEntryText(linkText)
		cleanDesc := cleanEntryText(entry.Description)

		// Don't repeat description if it's the same as the title
		if cleanDesc == cleanText {
			cleanDesc = ""
		}

		if cleanText != "" {
			if cleanDesc != "" {
				writer.WriteString(fmt.Sprintf("[%s](%s): %s\n", cleanText, entry.URL, cleanDesc))
			} else {
				writer.WriteString(fmt.Sprintf("[%s](%s)\n", cleanText, entry.URL))
			}
		} else {
			writer.WriteString(entry.URL + "\n")
		}
	}

	return nil
}

func cleanEntryText(text string) string {
	cleaned := strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' || r == '\t' {
			return ' '
		}
		return r
	}, text)
	cleaned = strings.Join(strings.Fields(cleaned), " ")
	return cleaned
}
