package fetcher

import (
	"bufio"
	"fmt"
	"os"
)

// GenerateLLMTxt writes extracted URLs to llm.txt file (NO fetching)
// Format: Simple list of URLs found on crawled pages
func GenerateLLMTxt(entries []LLMTxtEntry, outputPath string) error {
	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create llm.txt file: %w", err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	// Write header comment
	writer.WriteString("# llm.txt - Documentation URL Index\n")
	writer.WriteString("# Generated by DocFetch - List of discovered documentation URLs\n\n")

	// Track unique URLs to avoid duplicates
	seenURLs := make(map[string]bool)
	
	// Write each unique URL
	for _, entry := range entries {
		if entry.URL == "" {
			continue
		}
		
		// Skip if already written
		if seenURLs[entry.URL] {
			continue
		}
		seenURLs[entry.URL] = true
		
		// Write URL (one per line)
		writer.WriteString(entry.URL + "\n")
	}

	return nil
}